Task_1_1_1
Km1zZzoU/OOP pull request #1
Opened 2024-09-09 08:50 UTC by Km1zZzoU

2024-09-09 11:35 UTC, Sharapov-Maksim commented
Почему-то [CI](https://github.com/Km1zZzoU/OOP/actions/workflows/oop.yml) не запустился

2024-09-09 15:43 UTC, Sharapov-Maksim commented
Битый `.github/workflows/oop.yml`, сравните содержимое с [файлом](https://github.com/shadrina/OOP/blob/main/.github/workflows/oop.yml) из [инструкции](https://github.com/shadrina/OOP/tree/main#%D0%B8%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D0%B8-%D0%B4%D0%BB%D1%8F-%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F-workflow). Внимательнее следуйте инструкции

2024-09-09 16:53 UTC, Km1zZzoU commented
не понял, что произошло с oop.yml, я его перенес из склонированного репа из инструкции

не понимаю, за что ругается codestyle и build((((((

2024-09-09 16:57 UTC, Sharapov-Maksim commented
> не понимаю, за что ругается codestyle

Видите warning-и на вкладке [Files Changed](https://github.com/Km1zZzoU/OOP/pull/1/files) ?

2024-09-09 17:13 UTC, Sharapov-Maksim commented
Пробовали запускать `gradle javadoc`? В CI именно эта таска падает

В IDEA тут: 
![image](https://github.com/user-attachments/assets/99392a57-2a1d-4794-9090-90027bf7b476)

2024-09-09 17:33 UTC, Km1zZzoU commented
теперь да ошибок нет, build работает теперь, а checkstyle падает(

2024-09-10 03:07 UTC, Sharapov-Maksim commented
У каждой CI таски есть лог исполнения, поглядите в лог checkstyle, там есть checkstyle warning-и, которые почему-то не отображаются в Files Changed

2024-09-10 03:10 UTC, Sharapov-Maksim commented
И я на вкладке Files Changed всё ещё вижу неисправленные warning-и

Сейчас установлен лимит таких предупреждений - 10, после его достижения checkstyle завершается с ошибкой, не продолжая сканирование

2024-09-10 03:17 UTC, Km1zZzoU commented
не хватало точек в конце предложения...
исправил

2024-09-10 03:27 UTC, Sharapov-Maksim requested changes
Выдал некоторые замечания, исправляйте, комментируйте, запрашивайте повторное ревью

2024-09-10 03:27 UTC, Sharapov-Maksim commented on Task_1_1_1/src/main/java/org/nsu/syspro/HeapSort.java
> +         */
А чем вам не понравились однострочные комментарии (`//`)? Ну или хотя бы оставить закрывающие символы (`*/`) на той же строке?

2024-09-10 03:27 UTC, Sharapov-Maksim commented on Task_1_1_1/src/main/java/org/nsu/syspro/HeapSort.java
> +     * @param arr - arr
Javadoc мы пишем не для галочки, надо добавить осмысленный комментарий

2024-09-10 03:27 UTC, Sharapov-Maksim commented on Task_1_1_1/src/main/java/org/nsu/syspro/HeapSort.java
> +             * recursion))))
Мне кажется излишний комментарий

2024-09-10 03:27 UTC, Sharapov-Maksim commented on Task_1_1_1/src/main/java/org/nsu/syspro/HeapSort.java
> +     * @param arr - arr
Во всех подобных местах

2024-09-10 04:17 UTC, Sharapov-Maksim approved these changes

2024-09-10 04:17 UTC, merged