Task-1-1-2
Km1zZzoU/OOP pull request #2
Opened 2024-09-15 12:41 UTC by Km1zZzoU

2024-09-15 13:01 UTC, Sharapov-Maksim commented
Вы добавляйте ревьювера, когда готовы к ревью, или пишите что ещё не готово. А то я сижу смотрю ваш код а вы молча докомитываете что-то

2024-09-15 13:07 UTC, Sharapov-Maksim requested changes
Мягкий дедлайн зачтён, доделывайте

2024-09-15 13:07 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Utils.java
> +public class Utils {
Наследовать всё подряд от этого класса не стоит.

Разберём использования этого класса:

1. Поле `dictNames`. Используется в `Card`. Мапа создаётся каждый раз при создании любого наследника, то есть у каждого объекта (у каждой игры, раунда и даже у каждой карты) будет своя мапа. Но ведь мапа нужна только одна? Можно легко заменить статическим полем с мапой и статической функцией отображения
2. `wait()`. Используется в `Game`. Почему это instance-метод? Можно ведь сделать `static`.
3. Больше использований я не вижу, но зачем-то есть ещё отнаследованные `Deck` и `Cards`

Получается, что в классе нет никакой функциональности, которая нужна каждому отдельному наследнику

2024-09-15 13:07 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Cards.java
> +public class Cards extends Utils {
Видимо какой-то из `Deck` и `Cards` лишний

2024-09-15 13:14 UTC, Km1zZzoU commented
> Вы добавляйте ревьювера, когда готовы к ревью, или пишите что ещё не готово. А то я сижу смотрю ваш код а вы молча докомитываете что-то

Здравствуйте, у меня локально все работало, чутка поторопился с ревью

2024-09-18 07:02 UTC, Km1zZzoU commented
Здравствуйте, переписал почти все, посмотрите пожалуйста

2024-09-19 15:14 UTC, Sharapov-Maksim commented
Не забывайте, что если я задаю прямой вопрос в ревью, надо на него ответить

2024-09-19 15:54 UTC, Sharapov-Maksim requested changes
Замечания выдал, исправляйте.
Попрошу обратить пристальное внимание javadoc и поправить все, не только упомянутые мной

2024-09-19 15:54 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Game.java
> +            System.out.printf(resultMsg + " Счет %d:%d:%d\n", playerScore, drawScore, dealerScore);
А зачем делать `drawScore`? Мне как-то совсем не интуитивен такой формат счёта, но может это субъективно...

2024-09-19 15:54 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Game.java
> +            if (res == 1) {
Надо дать имена константам `-1`, `0`, `1`. Или можно завести `enum`

2024-09-19 15:54 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Utils.java
> +    public static String get(byte value) {
Ни по названию метода, ни по javadoc не понятно, что он делает

2024-09-19 15:54 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Deck.java
> +public class Deck extends Utils{
`extends Utils` ?

2024-09-19 15:54 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Cards.java
> + * array cards, have fields: cards, sum realsum (with/wthout  Ace).
Нужно писать понятные javadoc. Тут можно написать, зачем/кем используется этот класс.

Писать состав полей класса не нужно и даже плохо. У каждого публичного поля должен быть свой личный javadoc, а не публичные поля никому и не будут видны, о них никому извне не нужно ничего знать

2024-09-19 15:54 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Cards.java
> +public class Cards {
Если сделать название не таким общим, а, например, `PlayerCards` или `HandCards`, то сразу станет понятно зачем нужны объекты этого класса

2024-09-19 15:54 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Cards.java
> + * array cards, have fields: cards, sum realsum (with/wthout  Ace).
Замечания распространяется на все javadoc к классам вашего решения

2024-09-19 15:54 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Cards.java
> +     * Constructor, init cards = ArratList and sums.
Поправьте javadoc, сейчас он плохо читается. Опять таки, о полях нет толку писать здесь, это детали реализации

2024-09-19 15:54 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Deck.java
> +        Byte[] values = {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
Тут на каждом вызове конструктора будут создаваться эти массивы. Но они ведь константные и одинаковые для всех `Deck`, значит их можно разделить между всеми колодами, например с помощью `static` переменной

2024-09-19 15:54 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Deck.java
> +     * delete card and copy all cards after on index++.
Сделать javadoc читаемым

2024-09-19 15:54 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Game.java
> +    public Game() {
у конструктора нет использований, нужен ли он?)

2024-09-19 15:54 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Main.java
> +     * @param args idk
А что же всё таки такое `String[] args`?

2024-09-19 15:54 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Round.java
> +        dealerCards.append(deck.popCard());
![image](https://github.com/user-attachments/assets/ef848f26-9e20-41ca-9828-2903b871ea3f)
а у вас у дилера только одна карта

2024-09-19 15:54 UTC, Sharapov-Maksim commented on Task_1_1_2/src/test/java/org/nsu/Test.java
> +class Test {
Тестовый класс нужно называть в соответствии с классом, функциональность которого он тестирует. А сами разбивать по классам

2024-09-19 15:54 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Card.java
> +     * @param valueCard : 1 - 14 (1 - overAce, 11 - j ... 14 - Ace)
Давайте заведём либо набор именованых констант, либо (даже лучше) `enum` со значениями карт. Такой подход с `1 - 14` совсем плохо читается

2024-09-19 15:54 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Utils.java
> +    public static String get(byte value) {
Метод логически требуется именно классу `Card`, думаю ему там будет самое место

2024-09-19 15:54 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Deck.java
> +    public Card popCard() {
А что случится, если попросим `popCard()` у пустой колоды? Надо как-то обработать и тест добавить

2024-09-23 15:55 UTC, Km1zZzoU commented on Task_1_1_2/src/main/java/org/nsu/Game.java
> +class Round extends Game {
тут уже не использую, использовал просто чтобы дергать функцию или поле из game, забыл про static.
Наследование нужно для расширения функционала того или иного класса путем созданием новых классов от его самого. Также лучше подчеркивает структуру программы

2024-09-23 15:55 UTC, Km1zZzoU commented on Task_1_1_2/src/main/java/org/nsu/Utils.java
> +public class Utils {
исправил

2024-09-23 15:56 UTC, Km1zZzoU commented on Task_1_1_2/src/main/java/org/nsu/Cards.java
> +public class Cards extends Utils {
поправил

2024-09-23 15:56 UTC, Km1zZzoU commented on Task_1_1_2/src/main/java/org/nsu/Game.java
> +            System.out.printf(resultMsg + " Счет %d:%d:%d\n", playerScore, drawScore, dealerScore);
не знаю, захотелось, уже вырезал

2024-09-23 15:57 UTC, Km1zZzoU commented on Task_1_1_2/src/main/java/org/nsu/Utils.java
> +    public static String get(byte value) {
поправил

2024-09-23 15:57 UTC, Km1zZzoU commented on Task_1_1_2/src/main/java/org/nsu/Cards.java
> + * array cards, have fields: cards, sum realsum (with/wthout  Ace).
переписал

2024-09-23 15:57 UTC, Km1zZzoU commented on Task_1_1_2/src/main/java/org/nsu/Deck.java
> +public class Deck extends Utils{
уже убрал

2024-09-23 15:57 UTC, Km1zZzoU commented on Task_1_1_2/src/main/java/org/nsu/Card.java
> +     * @param valueCard : 1 - 14 (1 - overAce, 11 - j ... 14 - Ace)
завел

2024-09-23 15:57 UTC, Km1zZzoU commented on Task_1_1_2/src/test/java/org/nsu/Test.java
> +class Test {
переименовал

2024-09-23 15:58 UTC, Km1zZzoU commented on Task_1_1_2/src/main/java/org/nsu/Round.java
> +        dealerCards.append(deck.popCard());
у этой скрытой карты нет функциональности, по выданным условиям нет никакой разницы, закрытая карта или ее отсутствие. Но добавил ее отображение, чтобы смотрелось как в примере

2024-09-23 15:59 UTC, Km1zZzoU commented on Task_1_1_2/src/main/java/org/nsu/Main.java
> +     * @param args idk
input arguments

2024-09-23 15:59 UTC, Km1zZzoU commented on Task_1_1_2/src/main/java/org/nsu/Deck.java
> +     * delete card and copy all cards after on index++.
переделал

2024-09-23 15:59 UTC, Km1zZzoU commented on Task_1_1_2/src/main/java/org/nsu/Deck.java
> +        Byte[] values = {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
вынес в переменные

2024-09-23 15:59 UTC, Km1zZzoU commented on Task_1_1_2/src/main/java/org/nsu/Cards.java
> +     * Constructor, init cards = ArratList and sums.
поправил

2024-09-23 15:59 UTC, Km1zZzoU commented on Task_1_1_2/src/main/java/org/nsu/Cards.java
> +public class Cards {
изменил на HandCards

2024-09-23 16:00 UTC, Km1zZzoU commented on Task_1_1_2/src/main/java/org/nsu/Utils.java
> +    public static String get(byte value) {
согласен, перенес

2024-09-23 16:00 UTC, Km1zZzoU commented on Task_1_1_2/src/main/java/org/nsu/Deck.java
> +    public Card popCard() {
тест добавил, обрабатываю теперь

2024-09-23 16:01 UTC, Km1zZzoU commented
исправил все, что мог, понятия не имею как повысить % на utils и как тестировать остальной функционал round без игрока

2024-09-24 11:37 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Card.java
> +        return value > ten ? ten : value;
Второе использование `ten` здесь не логично. У вас поле `ten` в действительности означает индекс карт-десяток (т.е. переменная могла называться `RANK_INDEX_TEN`). А в методе вы возвращаете стоимость карты, а не индекс, поэтому использовать ту же именованную константу не правильно, ведь её значение совсем другое.

А вот с `enum` таких проблем бы не было, можно было бы хранить стоимость карты в объектах перечисления.
```
public enum Rank {
    TWO(2),
    ...
    ACE(11);

    public final int points;

    Rank(int points) {
        this.points = points;
    }
}
```

2024-09-24 11:37 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Game.java
> +class Round extends Game {
Но ведь чтобы вызывать методы, можно было в Round передать Game и работать с ним. В случае наследования класс не просто получает видимость полей/методов родительского класса, но и буквально перенимает это состояние и поведение от родительского класса - таким лучше не злоупотреблять. Хорошо, убрали не нужное наследование

2024-09-24 11:41 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Game.java
> +            if (res == 1) {
А в `org.nsu.Round#start` заиспользовали?

2024-09-24 11:57 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Round.java
> +    public int start() {
Исправить `@return` javadoc

2024-09-24 11:57 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Card.java
> +    public static String get(byte value) {
`get` -> `getName`

2024-09-24 11:57 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Card.java
> +    public static String get(byte value) {
Убрать `static`, использовать `this.value`, поправить использования в тестах

2024-09-24 11:57 UTC, Sharapov-Maksim commented on Task_1_1_2/src/test/java/org/nsu/TestBJ.java
> +class TestBJ {
Разбить на классы тестов в соответствии с тестируемыми классами приложения

2024-09-24 11:57 UTC, Sharapov-Maksim commented on Task_1_1_2/src/test/java/org/nsu/TestBJ.java
> +    void testWait() {
wait тестировать не надо, не понятно как это сделать правильно

на покрытие вспомогательных классов я не смотрю

2024-09-24 11:57 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Deck.java
> +    public Card popCard() {
Ещё добавить описание этого поведения в javadoc

2024-09-24 11:59 UTC, Sharapov-Maksim requested changes
Выдал новые замечания, и ответил на некоторые неразрешённые комментарии

2024-09-25 05:56 UTC, Km1zZzoU commented on Task_1_1_2/src/test/java/org/nsu/TestBJ.java
> +    void testWait() {
ок

2024-09-25 06:03 UTC, Km1zZzoU commented on Task_1_1_2/src/main/java/org/nsu/Round.java
> +    public int start() {
исправил

2024-09-25 06:27 UTC, Km1zZzoU commented on Task_1_1_2/src/main/java/org/nsu/Card.java
> +    public static String get(byte value) {
переписал

2024-09-25 06:27 UTC, Km1zZzoU commented on Task_1_1_2/src/test/java/org/nsu/TestBJ.java
> +class TestBJ {
разбил

2024-09-25 06:31 UTC, Km1zZzoU commented on Task_1_1_2/src/main/java/org/nsu/Card.java
> +        return value > ten ? ten : value;
поменял

2024-09-25 06:34 UTC, Km1zZzoU commented
исправил недочеты

2024-09-26 11:11 UTC, Km1zZzoU commented
не заметил, что не прошел чек стайл (не хватало точки в конце предложения), доревьювьте пожалуйста

2024-09-26 15:23 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Card.java
> +        return value > ten ? ten : value;
Только надо было сделать
```
return value > ten ? picture : value;
```
я это имел ввиду

2024-09-26 15:25 UTC, Km1zZzoU commented on Task_1_1_2/src/main/java/org/nsu/Card.java
> +        return value > ten ? ten : value;
а, понял

2024-09-26 15:25 UTC, Km1zZzoU commented on Task_1_1_2/src/test/java/org/nsu/TestBJ.java
> +class TestDeck {
хорошо

2024-09-26 15:31 UTC, Sharapov-Maksim requested changes
Нужно поправить замечания, ответить на вопрос

2024-09-26 15:31 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Card.java
> +        return new Card(type, value).getName() + " " + type + " (" + getCount() + ")";
А что помешало позвать `this.getName()`? Зачем копию текущего объекта создавать?
`getCount()` же получилось позвать...

**Расскажите в чём разница между методами объекта и статическими методами?**

2024-09-26 15:31 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/nsu/Card.java
> +        return value > picture ? picture : value;
Только надо было сделать
```
return value > ten ? picture : value;
```
я это имел ввиду

2024-09-26 15:31 UTC, Sharapov-Maksim commented on Task_1_1_2/src/test/java/org/nsu/TestBJ.java
> +class TestDeck {
Как вам и говорит, checkstyle, классы верхнего уровня нужно по разным файликам раскидывать

>[reviewdog] reported by reviewdog 🐶
Top-level class TestDeck has to reside in its own source file.

2024-09-26 15:40 UTC, Km1zZzoU commented on Task_1_1_2/src/main/java/org/nsu/Card.java
> +        return new Card(type, value).getName() + " " + type + " (" + getCount() + ")";
ничего, не помню уже, что смутило...

статические методы могут быть вызваны на самом классе, но при этом не имеют доступа к **не** _static_ полям, в то время как обычные методы выхываются только на объекте

2024-09-26 15:45 UTC, Km1zZzoU commented on Task_1_1_2/src/test/java/org/nsu/TestBJ.java
> +class TestDeck {
либо сделать внутренним?

2024-09-26 15:47 UTC, Km1zZzoU commented
исправил, ответил

2024-09-26 15:51 UTC, Sharapov-Maksim commented on Task_1_1_2/src/test/java/org/nsu/TestBJ.java
> +class TestDeck {
Ну, checkstyle действительно не ругается теперь. Но принято в разных файлах делать

2024-09-26 15:51 UTC, Sharapov-Maksim approved these changes
Задание засчитано, PR можно мёржить

2024-09-26 15:52 UTC, merged