Task_1_1_3
Km1zZzoU/OOP pull request #4
Opened 2024-09-28 13:00 UTC by Km1zZzoU

2024-09-28 13:10 UTC, Km1zZzoU commented
Задачу сделал, но ругается CL на непонятно что, посмотрите пожалуйста

2024-09-29 09:40 UTC, Sharapov-Maksim commented
Пробовали локально собирать проект через gradle?
Судя по ошибке, сейчас похоже не хватает `gradle/wrapper/gradle-wrapper.jar`
Можно сделать `gradle init` ([ссылка](https://docs.gradle.org/current/samples/sample_building_java_applications.html#run_the_init_task)). Или открыть проект в IDEA и загрузить gradle, нужные файлы сгенерируются автоматически

2024-09-29 09:43 UTC, Km1zZzoU commented
вы про это?
![изображение](https://github.com/user-attachments/assets/8eed0dbb-9a2f-480e-ac2b-9eb68bb2132f)

2024-09-29 10:02 UTC, Sharapov-Maksim commented
Да. Если `build` у вас проходит, значит и нужная иерархия файлов должна была сгенерироваться, нужно закоммитать оставшиеся файлы

2024-09-29 10:05 UTC, Km1zZzoU commented
да, вы правы

2024-09-29 12:14 UTC, Sharapov-Maksim requested changes
Хорошая работа, мягкий дедлайн зачтён, доделывайте

2024-09-29 12:14 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/org/nsu/syspro/Expression.java
> +    public abstract Double solve();
А чем `solve()` отличаеется от `eval(null)`, когда переменных и так нет? Стоит унифицировать эти два метода и оставить только `eval`

2024-09-29 12:14 UTC, Sharapov-Maksim commented on Task_1_1_3/src/test/java/org/nsu/syspro/Tests.java
> +            } catch (AssertionError e) {}
Тест странный. У вас `Assertions.assertNull(expr)` выдаёт ошибку (т.к. expr != null), вы её тут же ловите и тест завершается успешно

Надо поправить

2024-09-29 12:14 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/org/nsu/syspro/Expression.java
> +    public abstract Double eval(String s);
Протестировать все реализации `eval` из наследников

2024-10-03 04:21 UTC, Km1zZzoU commented on Task_1_1_3/src/main/java/org/nsu/syspro/Variable.java
> +        return null;
сделано

2024-10-03 04:21 UTC, Km1zZzoU commented on Task_1_1_3/src/main/java/org/nsu/syspro/Expression.java
> +    public abstract Double solve();
унифицировал

2024-10-03 04:36 UTC, Km1zZzoU commented on Task_1_1_3/src/main/java/org/nsu/syspro/Variable.java
> +        return null;
сделал

2024-10-03 11:30 UTC, Km1zZzoU commented on Task_1_1_3/src/main/java/org/nsu/syspro/Expression.java
> +    public abstract Double eval(String s);
тестирую

2024-10-03 11:33 UTC, Km1zZzoU commented
вроде все исправил все, можете смотреть

2024-10-03 16:34 UTC, Sharapov-Maksim requested changes

2024-10-03 16:34 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/org/nsu/syspro/Expression.java
>  public abstract class Expression {
А про это задание вы забыли? Я думал просто недоделали к мягкому дедлайну...

![image](https://github.com/user-attachments/assets/ca44b70e-fc0f-48b5-914c-d65a688829aa)

2024-10-03 16:34 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/org/nsu/syspro/Div.java
> +    }
Рекомендую самостоятельно запускать тесты с покрытием и отслеживать непокрытые места.

Это можно сделать, например, в IDEA:
![image](https://github.com/user-attachments/assets/19e21b1b-fd2e-4fbc-b476-b30e6d483cf6)
тогда, прямо в коде, строки, которые ни разу не запустились, пометятся красным
![image](https://github.com/user-attachments/assets/7b47e8a9-874b-42a3-b594-28e8d8a9d52c)

В общем, эти два метода надо покрыть

2024-10-07 07:27 UTC, Km1zZzoU commented on Task_1_1_3/src/main/java/org/nsu/syspro/Expression.java
>  public abstract class Expression {
да, уже добавил

2024-10-07 07:28 UTC, Km1zZzoU commented on Task_1_1_3/src/main/java/org/nsu/syspro/Div.java
> +    }
понял принял

2024-10-07 07:35 UTC, Km1zZzoU commented
парсер добавил, тесты обновил

2024-10-07 11:49 UTC, Sharapov-Maksim approved these changes
Задание зачтено

2024-10-09 13:41 UTC, merged