Task_1_2_1
Km1zZzoU/OOP pull request #6
Opened 2024-10-15 14:45 UTC by Km1zZzoU

2024-10-16 15:12 UTC, Sharapov-Maksim requested changes
Мягкий дедлайн зачтён, доделывайте

2024-10-21 06:00 UTC, Km1zZzoU commented on Taxk_1_2_1/src/main/java/org/nsu/syspro/MatrixGraph.java
> +    private final List<String> vertices = new ArrayList<>();
верно

2024-10-21 06:00 UTC, Km1zZzoU commented on Taxk_1_2_1/src/main/java/org/nsu/syspro/MatrixGraph.java
> +        vertices.add(vertex);
нет, ошибка в логике, исправлено

2024-10-21 18:33 UTC, Km1zZzoU commented on Taxk_1_2_1/src/main/java/org/nsu/syspro/Graph.java
> +    void addEdge(String source, String destination);
описал

2024-10-21 18:33 UTC, Km1zZzoU commented on Taxk_1_2_1/src/main/java/org/nsu/syspro/MatrixGraph.java
> +    }
придумал

2024-10-21 18:35 UTC, Km1zZzoU commented on Taxk_1_2_1/src/main/java/org/nsu/syspro/incidenceGraph.java
> +    private final List<String[]> edges = new ArrayList<>();
черновой вариант, переделал, (в новой реализации хешмапа нужна только для того чтобы не раздувать матрицу по напрасну (аллоцировать матрицу 10000х10000 для вершины 10000, когда можно просто отобразить в чиселки поменьше))

2024-10-21 18:37 UTC, Km1zZzoU commented on Taxk_1_2_1/src/main/java/org/nsu/syspro/Graph.java
> +    List<String> topologicalSort();
исправил

2024-10-21 20:01 UTC, Km1zZzoU commented
Для добавления нового способа представления графа, надо создать новый публичный класс от интерфейса Graph и реализовать все методы из контракта. Для добавления нового метода для графа, надо использовать методы из интерфейса, а в качестве типа использовать `G extends Graph`

2024-10-22 05:15 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/nsu/syspro/Utils.java
> +    }
А конструктор зачем?

2024-10-22 05:15 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/nsu/syspro/Utils.java
> +    public static String graphToString(Graph graph) {
По заданию, `graphToString`, `fromFile` и `fromString` должны быть частью интерфейса. Нужно перенести

2024-10-22 05:15 UTC, Sharapov-Maksim commented on Taxk_1_2_1/src/main/java/org/nsu/syspro/Graph.java
> +    void addEdge(String source, String destination);
Нужно описывать это в интерфейсе, и чтобы все реализации следовали этому описанию. Тогда в самих реализациях даже javadoc не потребуется дублировать

2024-10-22 05:39 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/nsu/syspro/Utils.java
> +    public static String graphToString(Graph graph) {
И лучше `toString` сделать instance-методом, а не статическим

2024-10-22 05:39 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/nsu/syspro/MatrixGraph.java
> +    }
Между вызовами `sizeUpMatrix` размер `vertexIndexMap.size()` может измениться как в положительную сторону, так и в отрицательную. Случай с отрицательным изменением не работает: сделайте тест, в котором в граф добавляется несколько вершин, затем все удаляются, а затем добавляется новая, убедитесь.

В целом, перекопировать весь граф на каждом добавлении вершины делает высокой ассимптотическую сложность операции. Давайте сделаем, чтобы размер матрицы мог увеличиваться только вверх, но не на единицу, а в два раза, чтобы перекопирования были относительно редкими

2024-10-22 05:39 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/nsu/syspro/Graph.java
> +    void removeEdge(Integer source, Integer destination);
Аналогично `addEdge`, описать что будет при отсутствии вершин.
И для других методов тоже надо описать краевые случаи

2024-10-22 05:39 UTC, Sharapov-Maksim commented on Taxk_1_2_1/src/main/java/org/nsu/syspro/ListGraph.java
> +        if (!(obj instanceof ListGraph)) return false;
От `equals` довольно сложно отказаться, учитывая что он есть в условиях задачи =)
> Не забудьте поддержать операции сравнения на равенство и вывода в строку.

2024-10-22 05:57 UTC, Sharapov-Maksim requested changes

2024-10-22 05:57 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/nsu/syspro/IncidenceGraph.java
> +    }
Аналогично `MatrixGraph`, перекопировать матрицу надо пореже чем при каждом добавлении вершины/ребра

2024-10-22 05:57 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/nsu/syspro/IncidenceGraph.java
> +            vertexIndexMap = newVertexIndexMap;
Уменьшать размер матрицы, мягко говоря, не очень-то удобно. Предлагаю вам этого не делать, на корректность это кажется повлиять не должно.

А если и делать, то, опять таки, не каждый раз. Я так понимаю, вы хотели таким образом добиться эффективной утилизации памяти, однако вместо этого у вас получился, наоборот, спам созданием матриц на каждой операции, что добавляет нагрузку на аллокатор и сборщик мусора.

2024-10-22 05:57 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/nsu/syspro/Utils.java
> +    }
Давайте этот метод тоже перенесём в Graph, сделаем публичным instance-методом. Тогда им можно (и нужно) будет в тестах воспользоваться

2024-10-22 05:57 UTC, Sharapov-Maksim commented on Task_1_2_1/src/test/java/org/nsu/syspro/Tests.java
> +                Utils.graphToString(graph));
Проверку графа через приведение к строке лучше избегать.
1. Это зависит от формата вывода, при его изменении нужно будет поправить кучу тестов, а не только тесты на `toString`
2. Если сломается `toString`, сломаются все тесты

Вместо этого пользуйтесь другими методами из интерфейса. Когда реализуете equals, можно будет сравнивать с ожидаемым графом

2024-10-22 06:35 UTC, Km1zZzoU commented on Task_1_2_1/src/main/java/org/nsu/syspro/Utils.java
> +    }
на его отстутсвие жаловался javadoc, добавил, чтобы не тревожил

2024-10-22 06:43 UTC, Km1zZzoU commented on Task_1_2_1/src/main/java/org/nsu/syspro/Utils.java
> +    public static String graphToString(Graph graph) {
Перенес, спасибо за замечание!

2024-10-22 06:49 UTC, Km1zZzoU commented on Task_1_2_1/src/test/java/org/nsu/syspro/Tests.java
> +                Utils.graphToString(graph));
какая разница? тогда все будет зависеть от метода equals, я думал этот метод нужен только для тестов, но там прекрасно справляется graphToString... формат вывода менять не собираюсь. как реализовать equals не повторяя алгоритм приведения к строке, не представляю

2024-10-22 06:53 UTC, Km1zZzoU commented on Task_1_2_1/src/main/java/org/nsu/syspro/Utils.java
> +    public static String graphToString(Graph graph) {
а зачем? это будет копипаста в методах, алгоритм пользуется универсальными методами -> не привязан к типам, зачем его выносить в классы реализаций?

2024-10-22 07:01 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/nsu/syspro/Utils.java
> +    public static String graphToString(Graph graph) {
А я не прошу выносить в классы реализаций, его можно вынести в `Graph`

2024-10-22 07:04 UTC, Km1zZzoU commented on Task_1_2_1/src/main/java/org/nsu/syspro/Graph.java
> +    void removeEdge(Integer source, Integer destination);
описал, логику исправил

2024-10-22 07:04 UTC, Km1zZzoU commented on Task_1_2_1/src/main/java/org/nsu/syspro/Utils.java
> +    }
зачем им пользоваться в тестах? graphToString все прекрасно тестирует

2024-10-22 07:09 UTC, Sharapov-Maksim commented on Task_1_2_1/src/test/java/org/nsu/syspro/Tests.java
> +                Utils.graphToString(graph));
> какая разница? тогда все будет зависеть от метода equals

Допустим, пункт 2. сомнительный, ок

> я думал этот метод нужен только для тестов, но там прекрасно справляется graphToString...

Этот метод нужен по заданию, его в любом случае делать, поэтому поправить тесты уже не так сложно

> формат вывода менять не собираюсь

В реальной жизни это обычно не только от ваших желаний зависит

> как реализовать equals не повторяя алгоритм приведения к строке, не представляю

Например: проверить что в графах равное число и индексы вершин, а затем для каждой вершины проверить совпадение её соседей в графах.

2024-10-22 08:40 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/nsu/syspro/IncidenceGraph.java
> +            vertexIndexMap = newVertexIndexMap;
Вы же не просто так изучали алгоритмы, а чтобы применять свои знания в будущем. Не понимаю почему это вызывает у вас сложности. У ФИТа тоже есть отдельные курсы про алгоритмы, не понял при чём это здесь.

+ вы не только ООП изучаете, но и программирование на Java. Поэтому не вижу ничего плохого в том, чтобы вы уже известные вам алгоритмы реализовывали на этом языке, в полном объёме.

Даже больше скажу, в следующем задании (1-2-2) вообще хеш-таблица будет, там явно прописано про алгоритмическую сложность и эффективное использование памяти.

2024-10-22 11:25 UTC, Km1zZzoU commented on Taxk_1_2_1/src/main/java/org/nsu/syspro/Graph.java
> +    void addEdge(String source, String destination);
ок

2024-10-22 11:25 UTC, Km1zZzoU commented on Taxk_1_2_1/src/main/java/org/nsu/syspro/ListGraph.java
> +        if (!(obj instanceof ListGraph)) return false;
ок

2024-10-22 11:34 UTC, Km1zZzoU commented on Task_1_2_1/src/main/java/org/nsu/syspro/IncidenceGraph.java
> +    }
ок

2024-10-22 12:37 UTC, Km1zZzoU commented
правки

2024-10-22 14:30 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/nsu/syspro/Graph.java
> +        return graphToString(gr1).equals(graphToString(gr2));
Не, так не пойдёт, надо [по честному](https://github.com/Km1zZzoU/OOP/pull/6#discussion_r1810075919) сравнить содержимое графов

2024-10-22 14:30 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/nsu/syspro/Utils.java
> +    }
В `equals` наверняка пригодится

2024-10-22 14:54 UTC, Km1zZzoU commented
Будь по вашему, equals переписал

2024-10-22 15:20 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/nsu/syspro/Graph.java
> +        return graphToString(gr1).equals(graphToString(gr2));
Но внутри этой итерации ведь разные вещи. Если хотите, можете саму итерацию выделить в общий код и переиспользовать в toString и equals

2024-10-22 15:21 UTC, Sharapov-Maksim approved these changes
Задание зачтено, PR можно мёржить

2024-10-22 15:22 UTC, merged